"use client";
import { useEffect, useMemo, useState } from "react";
import { useLocale, useTranslations } from "next-intl";
import { Pencil, Plus, Trash2 } from "lucide-react";
import { Table, type ColumnDef } from "@/components/shared/ui/Table";
import { FilterBar, type AppliedFilters } from "@/components/shared/ui/FilterBar";
import { Pagination } from "@/components/shared/ui/Pagination";
import { FormModal, type FormFieldDef, type TranslatableFieldDef, type TranslationEntry } from "@/components/shared/forms/FormModal";
import { DeleteConfirmModal } from "@/components/shared/forms/DeleteConfirmModal";
import { TableActions } from "@/components/shared/ui/TableActions";
import { TableActionItem } from "@/components/shared/ui/TableActionItem";
import ToggleSwitch from "@/components/shared/ui/ToggleSwitch";
import Select from "@/components/shared/ui/Select";
import { useListParams } from "@/hooks/useListParams";
import { useClub } from "@/domains/club/hooks/useClub";
import { useAuth } from "@/domains/auth/hooks/useAuth";
import { usePlayingSchedules } from "./hooks/usePlayingSchedules";
import type { PlayingSchedule, PlayingScheduleFilters } from "./types";
import { getTranslatedTitle } from "@/lib/translations";

const weekdays = [0,1,2,3,4,5,6];
export function PlayingSchedulesPageClient(){
 const locale=useLocale(),t=useTranslations("common"),tp=useTranslations("playingSchedule"); const {club,slug}=useClub(); const {hasPermission,isSuperAdmin}=useAuth();
 const canCreate=isSuperAdmin||hasPermission("playing_schedule","create",club?.id),canUpdate=isSuperAdmin||hasPermission("playing_schedule","update",club?.id),canDelete=isSuperAdmin||hasPermission("playing_schedule","delete",club?.id);
 const {params,setPage,setLimit,updateMany,reset}=useListParams<PlayingScheduleFilters>({defaultFilters:{search:"",weekday:undefined,is_active:undefined},defaultSortBy:"sort_order",defaultSortDir:"asc"}); const [draftWeekday,setDraftWeekday]=useState<number|undefined>(params.weekday); const [draftActive,setDraftActive]=useState<0|1|undefined>(params.is_active); useEffect(()=>setDraftWeekday(params.weekday),[params.weekday]);useEffect(()=>setDraftActive(params.is_active),[params.is_active]);
 const h=usePlayingSchedules(slug??"",params); const [open,setOpen]=useState(false),[selected,setSelected]=useState<PlayingSchedule|null>(null),[del,setDel]=useState<PlayingSchedule|null>(null); const close=()=>{setOpen(false);setSelected(null)};
 const fields:FormFieldDef[]=useMemo(()=>[{name:"weekday",label:tp("weekday"),type:"select",required:true,options:weekdays.map(x=>({value:String(x),label:tp(`weekday_${x}`)}))},{name:"court_name",label:tp("courtName"),type:"text",required:true},{name:"court_address",label:tp("courtAddress"),type:"text"},{name:"start_time",label:tp("startTime"),type:"time-select",required:true},{name:"end_time",label:tp("endTime"),type:"time-select",required:true},{name:"auto_generate",label:tp("autoGenerate"),type:"toggle"},{name:"weeks_ahead",label:tp("weeksAhead"),type:"number"},{name:"sort_order",label:t("sortOrder"),type:"number"},{name:"is_active",label:t("active"),type:"toggle"}], [t,tp]);
 const translatableFields:TranslatableFieldDef[]=useMemo(()=>[{name:"title",label:tp("titleField"),type:"text",required:true},{name:"note",label:tp("note"),type:"textarea"}],[tp]); const init=selected?{weekday:String(selected.weekday),court_name:selected.court_name,court_address:selected.court_address??"",start_time:selected.start_time,end_time:selected.end_time,auto_generate:selected.auto_generate?"1":"0",weeks_ahead:String(selected.weeks_ahead??""),sort_order:String(selected.sort_order),is_active:selected.is_active?"1":"0"}:{weekday:"1",court_name:"",court_address:"",start_time:"20:00",end_time:"22:00",auto_generate:"1",weeks_ahead:"8",sort_order:"1",is_active:"1"};
 const initialTranslations=selected?Object.fromEntries((selected.translations??[]).map(x=>[x.locale,{...x}])):{vi:{locale:"vi",title:"",note:""},en:{locale:"en",title:"",note:""}};
 const columns:ColumnDef<PlayingSchedule>[]=[{key:"no",label:t("no"),render:(_,i)=><span className="text-xs text-foreground-muted">{(params.page-1)*params.limit+i+1}</span>},{key:"title",label:tp("titleField"),render:r=><span className="font-medium text-foreground">{getTranslatedTitle(r.translations,locale)||"â€”"}</span>},{key:"weekday",label:tp("weekday"),render:r=>tp(`weekday_${r.weekday}`)},{key:"court",label:tp("courtName"),render:r=><div><p>{r.court_name}</p><p className="text-xs text-foreground-muted">{r.start_time} â€“ {r.end_time}</p></div>},{key:"is_active",label:t("status"),render:r=><ToggleSwitch checked={r.is_active} loading={h.togglingIds.has(r.id)} disabled={!canUpdate} onChange={()=>h.handleToggleStatus(r.id)}/> }];
 if(!club||!slug)return null; const extra=<><Select label={tp("weekday")} options={weekdays.map(x=>({value:String(x),label:tp(`weekday_${x}`)}))} value={draftWeekday===undefined?"":String(draftWeekday)} onChange={v=>setDraftWeekday(v===""?undefined:Number(v))} placeholder={t("all")}/><Select label={t("status")} options={[{value:"1",label:t("active")},{value:"0",label:t("inactive")}] } value={draftActive===undefined?"":String(draftActive)} onChange={v=>setDraftActive(v===""?undefined:Number(v) as 0|1)} placeholder={t("all")}/></>;
 return <div className="space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-xl font-semibold">{tp("title")}</h1><p className="text-sm text-foreground-muted">{tp("totalCount",{count:h.total.toLocaleString()})}</p></div>{canCreate&&<button onClick={()=>{setSelected(null);setOpen(true)}} className="flex items-center gap-2 rounded-xl bg-primary px-3.5 py-2 text-sm text-primary-foreground"><Plus className="h-4 w-4"/>{tp("create")}</button>}</div><FilterBar search={params.search} sortBy={params.sort_by} sortDir={params.sort_dir} sortOptions={[{value:"weekday",label:tp("weekday")},{value:"sort_order",label:t("sortOrder")},{value:"created_at",label:t("createdAt")}] } showStatusFilter={false} loading={h.isLoading} onApply={(f:AppliedFilters)=>updateMany({search:f.search,sort_by:f.sort_by,sort_dir:f.sort_dir,weekday:draftWeekday,is_active:draftActive})} onReset={()=>{setDraftWeekday(undefined);setDraftActive(undefined);reset()}} extraFilters={extra}/><Table columns={columns} data={h.data} loading={h.isLoading} keyExtractor={r=>r.id} renderActions={r=><TableActions>{canUpdate&&<TableActionItem icon={<Pencil className="h-4 w-4"/>} label={t("edit")} onClick={()=>{setSelected(r);setOpen(true)}}/>}{canDelete&&<TableActionItem icon={<Trash2 className="h-4 w-4"/>} label={t("delete")} variant="danger" onClick={()=>setDel(r)}/>}</TableActions>} emptyText={tp("notFound")}/><Pagination page={params.page} limit={params.limit} total={h.total} onPageChange={setPage} onLimitChange={setLimit}/><FormModal isOpen={open} onClose={close} onSubmit={async(v,tr)=>{const r=selected?await h.handleEdit(selected.id,v,tr):await h.handleCreate(v,tr);if(!r)close();return r}} title={selected?tp("edit"):tp("create")} submitting={selected?h.isUpdating:h.isCreating} isEdit={!!selected} fields={fields} translatableFields={translatableFields} initialValues={init} initialTranslations={initialTranslations}/><DeleteConfirmModal isOpen={!!del} title={t("deleteConfirmTitle")} description={t("deleteConfirmDesc")} message={del?tp("deleteConfirmMsg",{title:getTranslatedTitle(del.translations,locale)}):""} confirmText={t("delete")} cancelText={t("cancel")} onConfirm={()=>{if(del)h.handleDeleteConfirm(del.id);setDel(null)}} onCancel={()=>setDel(null)} loading={h.isDeleting}/></div>;
}


