"use client";

import { useMemo, useState } from "react";
import { Info, RotateCcw, TrendingUp } from "lucide-react";
import { Area, Bar, Brush, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { DashboardActivityPoint } from "../types";
import { DashboardCard, DashboardState } from "./DashboardCard";
import { useDashboardChartColors } from "./useDashboardChartColors";
import "./_group.css";

type SeriesKey = "total" | "male" | "female" | "groups";

export function ActivityInteractive({ data }: { data: DashboardActivityPoint[] }) {
  const colors = useDashboardChartColors();
  const [visible, setVisible] = useState<Record<SeriesKey, boolean>>({ total: true, male: true, female: true, groups: true });
  const summary = useMemo(() => ({ average: data.length ? data.reduce((sum, item) => sum + item.total, 0) / data.length : 0, peak: data.reduce((peak, item) => item.total > peak.total ? item : peak, data[0]) }), [data]);
  const series = [
    { key: "total" as const, label: "Tổng", color: colors.total },
    { key: "male" as const, label: "Nam", color: colors.male },
    { key: "female" as const, label: "Nữ", color: colors.female },
    { key: "groups" as const, label: "Nhóm", color: colors.groups },
  ];
  const reset = () => setVisible({ total: true, male: true, female: true, groups: true });

  return <DashboardCard icon={TrendingUp} title="Mức độ tham gia" description="Tổng người, nam, nữ và nhóm giao lưu trong khoảng lọc">
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-4 py-3 sm:px-6"><div className="flex items-center gap-2 text-xs text-foreground-muted"><Info className="size-3.5" />Dữ liệu theo khoảng thời gian ở phần đầu trang</div><div className="flex flex-wrap items-center justify-end gap-1.5">{series.map((item) => <button key={item.key} type="button" aria-pressed={visible[item.key]} onClick={() => setVisible((current) => ({ ...current, [item.key]: !current[item.key] }))} className={`flex items-center gap-1.5 rounded-full border px-3 py-1.5 text-xs transition-opacity ${visible[item.key] ? "border-border text-foreground" : "border-transparent text-foreground-muted opacity-40 line-through"}`}><span className="size-2 rounded-full" style={{ backgroundColor: item.color }} />{item.label}</button>)}<button type="button" onClick={reset} title="Đặt lại series" aria-label="Đặt lại series" className="flex size-7 items-center justify-center rounded-full text-foreground-muted hover:bg-background-muted hover:text-foreground"><RotateCcw className="size-3.5" /></button></div></div>
    <div className="grid divide-y divide-border border-b border-border sm:grid-cols-3 sm:divide-x sm:divide-y-0"><div className="px-4 py-4 sm:px-6"><p className="text-[10px] font-semibold uppercase tracking-wide text-foreground-muted">Trung bình</p><p className="mt-1 text-base font-bold text-foreground">{summary.average.toFixed(1).replace(".", ",")} <span className="text-xs font-medium text-foreground-muted">người/ngày</span></p></div><div className="px-4 py-4 sm:px-6"><p className="text-[10px] font-semibold uppercase tracking-wide text-foreground-muted">Cao nhất</p><p className="mt-1 text-base font-bold" style={{ color: colors.total }}>{summary.peak?.label ?? "—"} <span className="text-xs font-medium text-foreground-muted">· {summary.peak?.total ?? 0} người</span></p></div><div className="px-4 py-4 sm:px-6"><p className="text-[10px] font-semibold uppercase tracking-wide text-foreground-muted">Độ phủ dữ liệu</p><p className="mt-1 text-base font-bold" style={{ color: colors.total }}>{data.length} <span className="text-xs font-medium text-foreground-muted">ngày</span></p></div></div>
    {!data.length ? <DashboardState message="Chưa có dữ liệu trong khoảng thời gian này." /> : <div className="h-[310px] w-full px-2 pb-2 pt-5 sm:h-[380px] sm:px-6"><ResponsiveContainer width="100%" height="100%"><ComposedChart accessibilityLayer data={data} margin={{ top: 10, right: 8, left: -16, bottom: 4 }}><defs><linearGradient id="activity-total-area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={colors.total} stopOpacity={0.2} /><stop offset="100%" stopColor={colors.total} stopOpacity={0.02} /></linearGradient></defs><CartesianGrid stroke={colors.grid} strokeDasharray="2 5" vertical={false} /><XAxis dataKey="label" tick={{ fill: colors.foregroundMuted, fontSize: 10 }} tickLine={false} axisLine={false} minTickGap={22} /><YAxis allowDecimals={false} tick={{ fill: colors.foregroundMuted, fontSize: 10 }} tickLine={false} axisLine={false} /><Tooltip cursor={{ stroke: colors.borderStrong, strokeDasharray: "4 4" }} content={({ active, payload, label }) => active && payload?.length ? <div className="min-w-44 rounded-xl border border-border bg-background/95 p-3 shadow-xl backdrop-blur"><p className="mb-2 border-b border-border pb-2 text-sm font-semibold text-foreground">Ngày {label}</p>{payload.map((item) => <div key={String(item.dataKey ?? item.name)} className="flex items-center justify-between gap-5 py-1 text-xs"><span className="flex items-center gap-2 text-foreground-muted"><span className="size-2 rounded-full" style={{ backgroundColor: item.color }} />{item.name}</span><strong className="text-foreground">{item.value} người</strong></div>)}</div> : null} /><Area type="monotone" dataKey="total" name="Tổng" fill="url(#activity-total-area)" stroke={colors.total} strokeWidth={2.5} hide={!visible.total} animationDuration={900} /><Line type="monotone" dataKey="male" name="Nam" stroke={colors.male} strokeWidth={2.2} dot={false} activeDot={{ r: 5 }} hide={!visible.male} animationBegin={160} animationDuration={950} /><Line type="monotone" dataKey="female" name="Nữ" stroke={colors.female} strokeWidth={2.2} dot={false} activeDot={{ r: 5 }} hide={!visible.female} animationBegin={280} animationDuration={1000} /><Bar dataKey="groups" name="Nhóm" fill={colors.groups} radius={[6, 6, 2, 2]} maxBarSize={18} hide={!visible.groups} animationBegin={400} animationDuration={850} /><Brush dataKey="label" height={24} stroke={colors.total} fill={colors.backgroundSubtle} travellerWidth={9} tickFormatter={() => ""} /></ComposedChart></ResponsiveContainer></div>}
  </DashboardCard>;
}
